spellchecker: aspell
matrix:
- name: markdown
  sources:
    - README.md
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
      - .wordlists.txt
    output: dictionary/readme.dic
  pipeline:
  - pyspelling.filters.text
  default_encoding: utf-8
- name: Python Source
  sources:
  - ./**/*.py|!./dist/**/*.py
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .wordlists.txt
    output: dictionary/python.dic
  pipeline:
  - pyspelling.filters.python:
